[env:waveshare_rp2040_zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
board_build.core = earlephilhower
framework = arduino
monitor_speed = 9600
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0

board_build.usb_product = Teams Status Monitor
board_build.arduino.earlephilhower.usb_pid = 0x1234

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 9600
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D USB_PRODUCT="\"Teams Status Monitor\""
    -D USB_PID=0x1234
lib_deps = 
    adafruit/Adafruit NeoPixel @ ^1.12.0


[env:waveshare_rp2350_zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
board_build.core = earlephilhower
framework = arduino
monitor_speed = 9600
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0

board_build.usb_product = Teams Status Monitor
board_build.arduino.earlephilhower.usb_pid = 0x1234
