name: Build and Release Firmware

on:
  push:
    tags:
      - 'fw-v*' # Startet automatisch, wenn du ein Tag wie "fw-v1.0" erstellst
  workflow_dispatch: # Erlaubt den manuellen Start über den Browser

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Build firmware for RP2040
      run: pio run -e waveshare_rp2040_zero -d PlatformIO

    - name: Build firmware for ESP32-S3
      run: pio run -e seeed_xiao_esp32s3 -d PlatformIO

    - name: Build firmware for RP2350
      run: pio run -e waveshare_rp2350_zero -d PlatformIO

    - name: Rename Firmware Binaries
      run: |
        Rename-Item -Path "PlatformIO/.pio/build/waveshare_rp2040_zero/firmware.uf2" -NewName "RP2040_firmware.uf2"
        Rename-Item -Path "PlatformIO/.pio/build/seeed_xiao_esp32s3/firmware.bin" -NewName "ESP32_firmware.bin"
        Rename-Item -Path "PlatformIO/.pio/build/waveshare_rp2350_zero/firmware.uf2" -NewName "RP2350_firmware.uf2"
      shell: pwsh

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ReleaseAssets-Firmware
        path: |
          PlatformIO/.pio/build/waveshare_rp2040_zero/RP2040_firmware.uf2
          PlatformIO/.pio/build/seeed_xiao_esp32s3/ESP32_firmware.bin
          PlatformIO/.pio/build/waveshare_rp2350_zero/RP2350_firmware.uf2

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_type == 'tag' && github.ref_name || format('fw-v1.0.{0}', github.run_number) }}
        name: Release Firmware ${{ github.ref_type == 'tag' && github.ref_name || format('fw-v1.0.{0}', github.run_number) }}
        files: |
          PlatformIO/.pio/build/waveshare_rp2040_zero/RP2040_firmware.uf2
          PlatformIO/.pio/build/seeed_xiao_esp32s3/ESP32_firmware.bin
          PlatformIO/.pio/build/waveshare_rp2350_zero/RP2350_firmware.uf2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
