name: Build and Release App

on:
  push:
    tags:
      - 'app-v*' # Startet automatisch, wenn du ein Tag wie "app-v1.3.0" erstellst
  workflow_dispatch: # Erlaubt den manuellen Start über den Browser

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Publish .NET App (Single File)
      run: dotnet publish TeamsStatus.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish

    - name: Zip the Output
      run: Compress-Archive -Path ./publish/* -DestinationPath TeamsStatusMonitor_Windows_x64.zip

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ReleaseAssets-App
        path: TeamsStatusMonitor_Windows_x64.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_type == 'tag' && github.ref_name || format('app-v1.0.{0}', github.run_number) }}
        name: Release App ${{ github.ref_type == 'tag' && github.ref_name || format('app-v1.0.{0}', github.run_number) }}
        files: TeamsStatusMonitor_Windows_x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
